name: Docker

on:
  workflow_call: 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0
      
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: lucascdafonseca1
    # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_SECRET }}
